export * from './types'
export * from './client'
export * as authApi from './auth'
export * as camarasApi from './camaras'
export * as deteccionesApi from './detecciones'
export * as placasApi from './placas'
export * as watchlistApi from './watchlist'
export * as alertasApi from './alertas'
export * as auditoriaApi from './auditoria'
export * as configuracionApi from './configuracion'
